/* eslint-disable @typescript-eslint/no-explicit-any */
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
  Image
} from '@react-pdf/renderer'

// Register a better Google font
Font.register({
  family: 'Open Sans',
  fonts: [
    { src: 'https://fonts.gstatic.com/s/opensans/v27/mem8YaGs126MiZpBA-UFVZ0e.ttf' }
  ]
})

const styles = StyleSheet.create({
  page: {
    fontFamily: 'Open Sans',
    fontSize: 11,
    padding: 40,
    backgroundColor: '#fff',
    lineHeight: 1.6,
  },
  header: {
    textAlign: 'center',
    marginBottom: 20,
    borderBottom: '1 solid #ddd',
    paddingBottom: 10,
  },
  schoolName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1f2937'
  },
  reportTitle: {
    fontSize: 13,
    marginTop: 4,
    color: '#3b82f6'
  },
  infoGrid: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 15,
  },
  infoBlock: {
    width: '48%',
  },
  label: {
    fontWeight: 'bold',
    color: '#374151'
  },
  value: {
    marginBottom: 4
  },
  table: {
    marginTop: 20,
    border: '1 solid #ccc',
    borderRadius: 4,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#e5e7eb',
    padding: 8,
    borderBottom: '1 solid #ccc',
  },
  tableRow: {
    flexDirection: 'row',
    padding: 8,
    borderBottom: '1 solid #f1f1f1',
  },
  col: {
    flex: 1,
    fontSize: 10,
  },
  commentsSection: {
    marginTop: 20,
    paddingTop: 10,
    borderTop: '1 solid #ccc',
  },
  commentsText: {
    fontSize: 11,
    marginTop: 6,
  },
  chartImage: {
    marginTop: 20,
    width: '100%',
    height: 150,
    objectFit: 'contain'
  },
  footer: {
    marginTop: 30,
    textAlign: 'center',
    fontSize: 10,
    color: '#9ca3af'
  }
})

const StudentReportPDF = ({ report }: { report: any }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      {/* Header */}
      <View style={styles.header}>
        <Text style={styles.schoolName}>Maai Mahiu Secondary School</Text>
        <Text style={styles.reportTitle}>Student Report Card — {report.term} {report.year}</Text>
      </View>

      {/* Student Info */}
      <View style={styles.infoGrid}>
        <View style={styles.infoBlock}>
          <Text style={styles.label}>Student Name:</Text>
          <Text style={styles.value}>{report.student_name}</Text>

          <Text style={styles.label}>Class:</Text>
          <Text style={styles.value}>{report.class_name}</Text>
        </View>

        <View style={styles.infoBlock}>
          <Text style={styles.label}>Mean Score:</Text>
          <Text style={styles.value}>{report.mean_score}</Text>

          <Text style={styles.label}>KCSE Grade:</Text>
          <Text style={styles.value}>{report.kcse_grade}</Text>

          <Text style={styles.label}>Position:</Text>
          <Text style={styles.value}>#{report.position}</Text>

          <Text style={styles.label}>Class Average:</Text>
          <Text style={styles.value}>{report.class_average}</Text>
        </View>
      </View>

      {/* Subject Table */}
      <View style={styles.table}>
        <View style={styles.tableHeader}>
          <Text style={styles.col}>Subject</Text>
          <Text style={styles.col}>Average Score</Text>
          <Text style={styles.col}>Grade</Text>
        </View>

        {report.subjects.map((sub: any, index: number) => (
          <View key={index} style={styles.tableRow}>
            <Text style={styles.col}>{sub.subject_name}</Text>
            <Text style={styles.col}>{sub.average_score}</Text>
            <Text style={styles.col}>{sub.kcse_grade}</Text>
          </View>
        ))}
      </View>

      {/* Chart Image Placeholder (can be dynamic) */}
      {report.chartUrl && (
        <Image src={report.chartUrl} style={styles.chartImage} />
      )}

      {/* Teacher Comments */}
      <View style={styles.commentsSection}>
        <Text style={styles.label}>Teacher's Comments:</Text>
        <Text style={styles.commentsText}>
          {report.teacher_comments || 'Great progress this term. Keep working hard and stay focused!'}
        </Text>
      </View>

      {/* Footer */}
      <View style={styles.footer}>
        <Text>Generated by Maai Mahiu School Management System</Text>
      </View>
    </Page>
  </Document>
)

export default StudentReportPDF
