from app import db
from .user import User
from .teacher import Teacher
from .student import Student
from .parent import Parent
from .classroom import Classroom
from .subject import Subject
from .teacher_subject import TeacherSubject
from .class_assignment import ClassAssignment
from .grade import Grade
from .exam import Exam
from .announcement import Announcement
from .message import Message
from .announcement_read import AnnouncementRead
from .timetable_entry import TimetableEntry
from .exam_schedule import ExamSchedule
from .student_subject import StudentSelection