"""Removed class id

Revision ID: 0615352796aa
Revises: bf4d66cfa4cd
Create Date: 2025-07-17 10:28:00.885711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0615352796aa'
down_revision = 'bf4d66cfa4cd'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('teacher_subjects', schema=None) as batch_op:
        batch_op.drop_column('class_id')  # Automatically removes FK constraint
        batch_op.create_unique_constraint('uq_teacher_subject', ['teacher_id', 'subject_id'])

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'classrooms', ['class_id'], ['class_id'])
        batch_op.drop_constraint('uq_teacher_subject', type_='unique')

    # ### end Alembic commands ###
