"""Add subject_id to grades

Revision ID: 2e1668abc69e
Revises: 87ba2474c8eb
Create Date: 2025-07-17 13:17:26.781924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e1668abc69e'
down_revision = '87ba2474c8eb'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_grades_subject_id', 'subjects', ['subject_id'], ['subject_id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('subject_id')

    # ### end Alembic commands ###
