"""Remove user_id

Revision ID: 310220e3905d
Revises: aebdda164837
Create Date: 2025-07-08 11:32:28.851936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310220e3905d'
down_revision = 'aebdda164837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('receiver_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.alter_column('sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['receiver_id'], ['user_id'])
        batch_op.drop_column('sent_at')
        batch_op.drop_column('recipient_id')
        batch_op.drop_column('message_text')
        batch_op.drop_column('message_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('message_text', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('recipient_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('sent_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['recipient_id'], ['user_id'])
        batch_op.alter_column('sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('timestamp')
        batch_op.drop_column('content')
        batch_op.drop_column('receiver_id')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
