"""Settings

Revision ID: 332897372e36
Revises: 54ed6cc53e2a
Create Date: 2025-07-08 10:28:58.947337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332897372e36'
down_revision = '54ed6cc53e2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
