"""Add Teacher Column

Revision ID: 9db393974457
Revises: cecc451676f9
Create Date: 2025-07-10 10:56:30.791840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9db393974457'
down_revision = 'cecc451676f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=True))
        # FIX: Provide a unique name for the foreign key constraint
        batch_op.create_foreign_key('fk_exams_teacher_id', 'teachers', ['teacher_id'], ['teacher_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        # FIX: Use the same unique name for dropping the foreign key constraint
        batch_op.drop_constraint('fk_exams_teacher_id', type_='foreignkey')
        batch_op.drop_column('teacher_id')

    # ### end Alembic commands ###