"""removed columns

Revision ID: c1a1911d6a2a
Revises: 0615352796aa
Create Date: 2025-07-17 12:36:49.551705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1a1911d6a2a'
down_revision = '0615352796aa'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_column('class_id')
        batch_op.drop_column('subject_id')
        batch_op.drop_column('teacher_id')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('subject_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('class_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'subjects', ['subject_id'], ['subject_id'])
        batch_op.create_foreign_key(None, 'classrooms', ['class_id'], ['class_id'])
        batch_op.create_foreign_key(None, 'teachers', ['teacher_id'], ['teacher_id'])

    # ### end Alembic commands ###
