"""remoce rel

Revision ID: e0806a27210a
Revises: 2e1668abc69e
Create Date: 2025-07-17 14:13:43.818758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0806a27210a'
down_revision = '2e1668abc69e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_grades_subject_id'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_grades_exam_schedule_id'), type_='foreignkey')
        batch_op.drop_column('subject_id')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('subject_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_grades_exam_schedule_id'), 'exam_schedules', ['exam_schedule_id'], ['id'])
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['student_id'])
        batch_op.create_foreign_key(batch_op.f('fk_grades_subject_id'), 'subjects', ['subject_id'], ['subject_id'])

    # ### end Alembic commands ###
