"""Add exam_schedules table

Revision ID: e62a8d2df8ac
Revises: 481183191c68
Create Date: 2025-07-17 12:54:51.237553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e62a8d2df8ac'
down_revision = '481183191c68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('class_assignment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_assignment_id'], ['class_assignments.id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'class_assignment_id', name='uq_exam_assignment')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_schedules')
    # ### end Alembic commands ###
