"""add student 

Revision ID: eebc4ba45b9b
Revises: 72c7bf38c24b
Create Date: 2025-07-17 14:37:55.526343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eebc4ba45b9b'
down_revision = '72c7bf38c24b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - manually fixed ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=False))
        # Give the foreign key a name (e.g., fk_grades_student_id)
        batch_op.create_foreign_key('fk_grades_student_id', 'students', ['student_id'], ['student_id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - manually fixed ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        # Use the same name you gave above
        batch_op.drop_constraint('fk_grades_student_id', type_='foreignkey')
        batch_op.drop_column('student_id')
    # ### end Alembic commands ###
